apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: grpc-dotnet-container
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        app: weather-forecast
        service: backend
    spec:
      containers:
          name: backend
          image: jp.icr.io/ira-tok/backend:v1
          resources:
            limits:
              cpu: 1
              memory: "2G"
          ports:
            containerPort: 80
          env:
              name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: grpc-dotnet-container
    service: backend
spec:
  clusterIP: None # Headless service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: backend